### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by EugeneHerasymchuk** [eddyerburgh/avoriaz-karma-mocha-example#2]
On [docs page](https://eddyerburgh.gitbooks.io/avoriaz/content/) in `Call DOM events on a child` section  you have `bar.dispatch('click');`. 
Change it to `bar.trigger('click'); `
Thanks!

**Comment by eddyerburgh** [comment]
Would you be able to make a PR implementing the change? The file is in the avoriaz repo -https://github.com/eddyerburgh/avoriaz/tree/master/docs

**Comment by eddyerburgh** [comment]
Closed with - https://github.com/eddyerburgh/avoriaz/commit/9281fbf126d24901dd5f0a4e8f9684a9692ce8b2
Thanks 👍
