### ISSUE TITLE
npm run lint:fix script.failing

### ISSUE THREAD

**Issue by ghost** [eddyerburgh/avoriaz-karma-mocha-example#3]
yves$ npm run lint:fix

> avoriaz-karma-mocha-example@1.0.0 lint:fix avoriaz-karma-mocha-example
> standard --env mocha --fix

standard: Use JavaScript Standard Style (https://standardjs.com)
  avoriaz-karma-mocha-example/test/unit/karma.conf.js:9:5: 'utils' is assigned a value but never used.
  avoriaz-karma-mocha-example/test/unit/specs/Foo.spec.js:8:5: 'expect' is not defined.
  avoriaz-karma-mocha-example/test/unit/specs/Foo.spec.js:14:5: 'expect'is not defined.
  avoriaz-karma-mocha-example/test/unit/specs/Foo.spec.js:24:5: 'expect'is not defined.
  avoriaz-karma-mocha-example/test/unit/specs/Foo.spec.js:31:5: 'expect'is not defined.
  avoriaz-karma-mocha-example/test/unit/specs/Foo.spec.js:37:5: 'expect'is not defined.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! avoriaz-karma-mocha-example@1.0.0 lint:fix: `standard --env mocha --fix`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the avoriaz-karma-mocha-example@1.0.0 lint:fix script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by eddyerburgh** [comment]
Could you make a PR?

You need to add `"env": "mocha"` to the `.eslintrc`

**Comment by ghost** [comment]
solved w package.json updates 👍 
    "eslint-plugin-html": "^3.0.0",      //  not "eslint-plugin-html": "^1.3.0"

and added 
    "eslint-plugin-vue": "^2.1.0",
